"""Pydantic data models for the RAG subsystem.

All models are immutable (``frozen=True``) so they can be safely passed
between threads, cached, and serialised without accidental mutation.
"""

from __future__ import annotations

import uuid
from typing import Any

from pydantic import BaseModel, Field


class DocumentChunk(BaseModel):
    """A semantically coherent slice of a source document.

    Each chunk belongs to one of two levels:

    * ``small`` — optimised for dense retrieval (~256 tokens).  Small chunks
      are what the retriever actually searches over.
    * ``big`` — the enclosing logical section (~1024 tokens).  After
      retrieval the engine follows ``parent_chunk_id`` to fetch the big
      chunk and uses *that* as the LLM context, giving the model enough
      surrounding information to produce a grounded answer.
    """

    chunk_id: str = Field(
        default_factory=lambda: uuid.uuid4().hex[:12],
        description="Unique 12-char hex identifier for this chunk.",
    )
    file_id: str = Field(
        ...,
        description="Source document identifier (typically the PDF stem).",
    )
    text: str = Field(
        ...,
        description="The chunk text content.",
    )
    heading_path: list[str] = Field(
        default_factory=list,
        description="Breadcrumb trail of Markdown headings enclosing this chunk, "
                    "e.g. ``['第三章 违约责任', '第107条 继续履行']``.",
    )
    chunk_level: str = Field(
        default="small",
        description="Either ``'small'`` (retrieval-optimised) or ``'big'`` "
                    "(context-optimised).",
    )
    parent_chunk_id: str | None = Field(
        default=None,
        description="When ``chunk_level='small'`` this points to the enclosing "
                    "big chunk used for context assembly.",
    )
    page_number: int | None = Field(
        default=None,
        description="Approximate 1-based page number where this chunk originates.",
    )
    char_start: int = Field(
        default=0,
        description="Character offset of this chunk's text in the source document.",
    )
    char_end: int = Field(
        default=0,
        description="Character offset of the end of this chunk's text.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary extra metadata (table indicators, image captions, "
                    "detected language, etc.).",
    )
    embedding: list[float] | None = Field(
        default=None,
        description="Pre-computed dense embedding vector (L2-normalised).",
    )

    model_config = {"frozen": True}


class RetrievalResult(BaseModel):
    """A single chunk retrieved by the hybrid search pipeline, with scores."""

    chunk: DocumentChunk = Field(..., description="The retrieved chunk.")
    dense_score: float = Field(
        default=0.0,
        description="Cosine-similarity score from the dense (vector) index.",
    )
    sparse_score: float = Field(
        default=0.0,
        description="BM25 score from the sparse (keyword) index.",
    )
    hybrid_score: float = Field(
        default=0.0,
        description="Fused score after Reciprocal Rank Fusion (RRF).",
    )
    rerank_score: float | None = Field(
        default=None,
        description="Cross-encoder relevance score after re-ranking. "
                    "Higher is more relevant.",
    )
    final_score: float = Field(
        default=0.0,
        description="Weighted final score used for ordering: "
                    "``0.7 * rerank_score + 0.3 * hybrid_score``.",
    )

    model_config = {"frozen": False}


class QueryPlan(BaseModel):
    """The result of query analysis: should we retrieve, and if so, how?"""

    original_query: str = Field(..., description="The user's raw query string.")
    rewritten_queries: list[str] = Field(
        default_factory=list,
        description="One or more reformulated queries for better retrieval. "
                    "May include keyword-style, question-style, and HyDE variants.",
    )
    hyde_doc: str | None = Field(
        default=None,
        description="Hypothetical Document Embedding — a synthetic answer "
                    "generated by the LLM to bridge the vocabulary gap.",
    )
    needs_retrieval: bool = Field(
        default=True,
        description="Self-RAG decision: ``False`` when the query can be answered "
                    "from the model's parametric knowledge alone.",
    )
    strategy: str = Field(
        default="retrieve",
        description="One of ``'direct'`` (no retrieval), ``'retrieve'`` "
                    "(standard RAG), ``'decompose'`` (multi-hop, not yet implemented).",
    )

    model_config = {"frozen": True}


class RAGResponse(BaseModel):
    """The final answer returned to the user, with full provenance."""

    answer: str = Field(..., description="The LLM-generated answer text.")
    sources: list[RetrievalResult] = Field(
        default_factory=list,
        description="Retrieved chunks that informed the answer, ordered by "
                    "relevance.",
    )
    query_plan: QueryPlan | None = Field(
        default=None,
        description="The query analysis that drove retrieval.",
    )
    elapsed_seconds: float = Field(
        default=0.0,
        description="Wall-clock time for the entire query pipeline.",
    )

    model_config = {"frozen": True}


class ChatMessage(BaseModel):
    """A single turn in a multi-turn conversation."""

    role: str = Field(
        ...,
        description="Either ``'user'`` or ``'assistant'``.",
    )
    content: str = Field(
        ...,
        description="The message text.",
    )
    sources: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Sources that informed this message (assistant role only).",
    )

    model_config = {"frozen": True}


class ChatResponse(BaseModel):
    """Response to a multi-turn chat message."""

    session_id: str = Field(..., description="Conversation session identifier.")
    answer: str = Field(..., description="The LLM-generated answer.")
    sources: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Sources that informed this answer.",
    )
    turn_number: int = Field(
        default=1,
        description="Which turn this is in the conversation (1-indexed).",
    )
    query_plan: dict[str, Any] | None = Field(
        default=None,
        description="The query analysis that drove retrieval.",
    )
    elapsed_seconds: float = 0.0

    model_config = {"frozen": True}
